version: '3'

services:
  image_resize_app:
    build: .
    depends_on:
      - redis
    ports:
      - 8000:8000
    expose:
      - "8000"

  celery:
    build: .
    command: celery -A main worker -l info
    volumes:
      - .:/app/code
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - "6379"

volumes:
  redis_data: